apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend 
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template: 
    spec: 
      containers:
      - name: front
        image: gcr.io/my-krm/cymbal-bank/release/frontend:d41f0b6
        env:
        - name: ENABLE_TRACING
          value: "true"
        - name: LOG_LEVEL
          value: "info"
